# Netlify Configuration for Zoho-IT Asset Tracker

[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# API Redirects - Redirect API calls to your backend server
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-server.herokuapp.com/api/:splat"
  status = 200
  force = true

# SPA Fallback - Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
